export class CurrencyMetadata {
  alphaCode: string;
  numCode: string;
  minorUnit: number | null;
  fullName: string;

  /* NOTE: have to do this so we can use `instanceof` on the objects */
  constructor(params) {
    this.alphaCode = params.alphaCode;
    this.numCode = params.numCode;
    this.minorUnit = params.minorUnit;
    this.fullName = params.fullName;
  }
}

export const CURRENCY_CODE_MAP : Array<CurrencyMetadata> = [
  new CurrencyMetadata({
    alphaCode: "AED",
    numCode: "784",
    minorUnit: 2,
    fullName: "UAE Dirham",
  }),
  new CurrencyMetadata({
    alphaCode: "AFN",
    numCode: "971",
    minorUnit: 2,
    fullName: "Afghani",
  }),
  new CurrencyMetadata({
    alphaCode: "ALL",
    numCode: "008",
    minorUnit: 2,
    fullName: "Lek",
  }),
  new CurrencyMetadata({
    alphaCode: "AMD",
    numCode: "051",
    minorUnit: 2,
    fullName: "Armenian Dram",
  }),
  new CurrencyMetadata({
    alphaCode: "ANG",
    numCode: "532",
    minorUnit: 2,
    fullName: "Netherlands Antillean Guilder",
  }),
  new CurrencyMetadata({
    alphaCode: "AOA",
    numCode: "973",
    minorUnit: 2,
    fullName: "Kwanza",
  }),
  new CurrencyMetadata({
    alphaCode: "ARS",
    numCode: "032",
    minorUnit: 2,
    fullName: "Argentine Peso",
  }),
  new CurrencyMetadata({
    alphaCode: "AUD",
    numCode: "036",
    minorUnit: 2,
    fullName: "Australian Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "AWG",
    numCode: "533",
    minorUnit: 2,
    fullName: "Aruban Florin",
  }),
  new CurrencyMetadata({
    alphaCode: "AZN",
    numCode: "944",
    minorUnit: 2,
    fullName: "Azerbaijan Manat",
  }),
  new CurrencyMetadata({
    alphaCode: "BAM",
    numCode: "977",
    minorUnit: 2,
    fullName: "Convertible Mark",
  }),
  new CurrencyMetadata({
    alphaCode: "BBD",
    numCode: "052",
    minorUnit: 2,
    fullName: "Barbados Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "BDT",
    numCode: "050",
    minorUnit: 2,
    fullName: "Taka",
  }),
  new CurrencyMetadata({
    alphaCode: "BGN",
    numCode: "975",
    minorUnit: 2,
    fullName: "Bulgarian Lev",
  }),
  new CurrencyMetadata({
    alphaCode: "BHD",
    numCode: "048",
    minorUnit: 3,
    fullName: "Bahraini Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "BIF",
    numCode: "108",
    minorUnit: 0,
    fullName: "Burundi Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "BMD",
    numCode: "060",
    minorUnit: 2,
    fullName: "Bermudian Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "BND",
    numCode: "096",
    minorUnit: 2,
    fullName: "Brunei Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "BOB",
    numCode: "068",
    minorUnit: 2,
    fullName: "Boliviano",
  }),
  new CurrencyMetadata({
    alphaCode: "BOV",
    numCode: "984",
    minorUnit: 2,
    fullName: "Mvdol",
  }),
  new CurrencyMetadata({
    alphaCode: "BRL",
    numCode: "986",
    minorUnit: 2,
    fullName: "Brazilian Real",
  }),
  new CurrencyMetadata({
    alphaCode: "BSD",
    numCode: "044",
    minorUnit: 2,
    fullName: "Bahamian Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "BTN",
    numCode: "064",
    minorUnit: 2,
    fullName: "Ngultrum",
  }),
  new CurrencyMetadata({
    alphaCode: "BWP",
    numCode: "072",
    minorUnit: 2,
    fullName: "Pula",
  }),
  new CurrencyMetadata({
    alphaCode: "BYN",
    numCode: "933",
    minorUnit: 2,
    fullName: "Belarusian Ruble",
  }),
  new CurrencyMetadata({
    alphaCode: "BZD",
    numCode: "084",
    minorUnit: 2,
    fullName: "Belize Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "CAD",
    numCode: "124",
    minorUnit: 2,
    fullName: "Canadian Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "CDF",
    numCode: "976",
    minorUnit: 2,
    fullName: "Congolese Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "CHE",
    numCode: "947",
    minorUnit: 2,
    fullName: "WIR Euro",
  }),
  new CurrencyMetadata({
    alphaCode: "CHF",
    numCode: "756",
    minorUnit: 2,
    fullName: "Swiss Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "CHW",
    numCode: "948",
    minorUnit: 2,
    fullName: "WIR Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "CLF",
    numCode: "990",
    minorUnit: 4,
    fullName: "Unidad de Fomento",
  }),
  new CurrencyMetadata({
    alphaCode: "CLP",
    numCode: "152",
    minorUnit: 0,
    fullName: "Chilean Peso",
  }),
  new CurrencyMetadata({
    alphaCode: "CNY",
    numCode: "156",
    minorUnit: 2,
    fullName: "Yuan Renminbi",
  }),
  new CurrencyMetadata({
    alphaCode: "COP",
    numCode: "170",
    minorUnit: 2,
    fullName: "Colombian Peso",
  }),
  new CurrencyMetadata({
    alphaCode: "COU",
    numCode: "970",
    minorUnit: 2,
    fullName: "Unidad de Valor Real",
  }),
  new CurrencyMetadata({
    alphaCode: "CRC",
    numCode: "188",
    minorUnit: 2,
    fullName: "Costa Rican Colon",
  }),
  new CurrencyMetadata({
    alphaCode: "CUC",
    numCode: "931",
    minorUnit: 2,
    fullName: "Peso Convertible",
  }),
  new CurrencyMetadata({
    alphaCode: "CUP",
    numCode: "192",
    minorUnit: 2,
    fullName: "Cuban Peso",
  }),
  new CurrencyMetadata({
    alphaCode: "CVE",
    numCode: "132",
    minorUnit: 2,
    fullName: "Cabo Verde Escudo",
  }),
  new CurrencyMetadata({
    alphaCode: "CZK",
    numCode: "203",
    minorUnit: 2,
    fullName: "Czech Koruna",
  }),
  new CurrencyMetadata({
    alphaCode: "DJF",
    numCode: "262",
    minorUnit: 0,
    fullName: "Djibouti Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "DKK",
    numCode: "208",
    minorUnit: 2,
    fullName: "Danish Krone",
  }),
  new CurrencyMetadata({
    alphaCode: "DOP",
    numCode: "214",
    minorUnit: 2,
    fullName: "Dominican Peso",
  }),
  new CurrencyMetadata({
    alphaCode: "DZD",
    numCode: "012",
    minorUnit: 2,
    fullName: "Algerian Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "EGP",
    numCode: "818",
    minorUnit: 2,
    fullName: "Egyptian Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "ERN",
    numCode: "232",
    minorUnit: 2,
    fullName: "Nakfa",
  }),
  new CurrencyMetadata({
    alphaCode: "ETB",
    numCode: "230",
    minorUnit: 2,
    fullName: "Ethiopian Birr",
  }),
  new CurrencyMetadata({
    alphaCode: "EUR",
    numCode: "978",
    minorUnit: 2,
    fullName: "Euro",
  }),
  new CurrencyMetadata({
    alphaCode: "FJD",
    numCode: "242",
    minorUnit: 2,
    fullName: "Fiji Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "FKP",
    numCode: "238",
    minorUnit: 2,
    fullName: "Falkland Islands Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "GBP",
    numCode: "826",
    minorUnit: 2,
    fullName: "Pound Sterling",
  }),
  new CurrencyMetadata({
    alphaCode: "GEL",
    numCode: "981",
    minorUnit: 2,
    fullName: "Lari",
  }),
  new CurrencyMetadata({
    alphaCode: "GHS",
    numCode: "936",
    minorUnit: 2,
    fullName: "Ghana Cedi",
  }),
  new CurrencyMetadata({
    alphaCode: "GIP",
    numCode: "292",
    minorUnit: 2,
    fullName: "Gibraltar Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "GMD",
    numCode: "270",
    minorUnit: 2,
    fullName: "Dalasi",
  }),
  new CurrencyMetadata({
    alphaCode: "GNF",
    numCode: "324",
    minorUnit: 0,
    fullName: "Guinean Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "GTQ",
    numCode: "320",
    minorUnit: 2,
    fullName: "Quetzal",
  }),
  new CurrencyMetadata({
    alphaCode: "GYD",
    numCode: "328",
    minorUnit: 2,
    fullName: "Guyana Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "HKD",
    numCode: "344",
    minorUnit: 2,
    fullName: "Hong Kong Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "HNL",
    numCode: "340",
    minorUnit: 2,
    fullName: "Lempira",
  }),
  new CurrencyMetadata({
    alphaCode: "HRK",
    numCode: "191",
    minorUnit: 2,
    fullName: "Kuna",
  }),
  new CurrencyMetadata({
    alphaCode: "HTG",
    numCode: "332",
    minorUnit: 2,
    fullName: "Gourde",
  }),
  new CurrencyMetadata({
    alphaCode: "HUF",
    numCode: "348",
    minorUnit: 2,
    fullName: "Forint",
  }),
  new CurrencyMetadata({
    alphaCode: "IDR",
    numCode: "360",
    minorUnit: 2,
    fullName: "Rupiah",
  }),
  new CurrencyMetadata({
    alphaCode: "ILS",
    numCode: "376",
    minorUnit: 2,
    fullName: "New Israeli Sheqel",
  }),
  new CurrencyMetadata({
    alphaCode: "INR",
    numCode: "356",
    minorUnit: 2,
    fullName: "Indian Rupee",
  }),
  new CurrencyMetadata({
    alphaCode: "IQD",
    numCode: "368",
    minorUnit: 3,
    fullName: "Iraqi Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "IRR",
    numCode: "364",
    minorUnit: 2,
    fullName: "Iranian Rial",
  }),
  new CurrencyMetadata({
    alphaCode: "ISK",
    numCode: "352",
    minorUnit: 0,
    fullName: "Iceland Krona",
  }),
  new CurrencyMetadata({
    alphaCode: "JMD",
    numCode: "388",
    minorUnit: 2,
    fullName: "Jamaican Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "JOD",
    numCode: "400",
    minorUnit: 3,
    fullName: "Jordanian Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "JPY",
    numCode: "392",
    minorUnit: 0,
    fullName: "Yen",
  }),
  new CurrencyMetadata({
    alphaCode: "KES",
    numCode: "404",
    minorUnit: 2,
    fullName: "Kenyan Shilling",
  }),
  new CurrencyMetadata({
    alphaCode: "KGS",
    numCode: "417",
    minorUnit: 2,
    fullName: "Som",
  }),
  new CurrencyMetadata({
    alphaCode: "KHR",
    numCode: "116",
    minorUnit: 2,
    fullName: "Riel",
  }),
  new CurrencyMetadata({
    alphaCode: "KMF",
    numCode: "174",
    minorUnit: 0,
    fullName: "Comorian Franc ",
  }),
  new CurrencyMetadata({
    alphaCode: "KPW",
    numCode: "408",
    minorUnit: 2,
    fullName: "North Korean Won",
  }),
  new CurrencyMetadata({
    alphaCode: "KRW",
    numCode: "410",
    minorUnit: 0,
    fullName: "Won",
  }),
  new CurrencyMetadata({
    alphaCode: "KWD",
    numCode: "414",
    minorUnit: 3,
    fullName: "Kuwaiti Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "KYD",
    numCode: "136",
    minorUnit: 2,
    fullName: "Cayman Islands Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "KZT",
    numCode: "398",
    minorUnit: 2,
    fullName: "Tenge",
  }),
  new CurrencyMetadata({
    alphaCode: "LAK",
    numCode: "418",
    minorUnit: 2,
    fullName: "Lao Kip",
  }),
  new CurrencyMetadata({
    alphaCode: "LBP",
    numCode: "422",
    minorUnit: 2,
    fullName: "Lebanese Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "LKR",
    numCode: "144",
    minorUnit: 2,
    fullName: "Sri Lanka Rupee",
  }),
  new CurrencyMetadata({
    alphaCode: "LRD",
    numCode: "430",
    minorUnit: 2,
    fullName: "Liberian Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "LSL",
    numCode: "426",
    minorUnit: 2,
    fullName: "Loti",
  }),
  new CurrencyMetadata({
    alphaCode: "LYD",
    numCode: "434",
    minorUnit: 3,
    fullName: "Libyan Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "MAD",
    numCode: "504",
    minorUnit: 2,
    fullName: "Moroccan Dirham",
  }),
  new CurrencyMetadata({
    alphaCode: "MDL",
    numCode: "498",
    minorUnit: 2,
    fullName: "Moldovan Leu",
  }),
  new CurrencyMetadata({
    alphaCode: "MGA",
    numCode: "969",
    minorUnit: 2,
    fullName: "Malagasy Ariary",
  }),
  new CurrencyMetadata({
    alphaCode: "MKD",
    numCode: "807",
    minorUnit: 2,
    fullName: "Denar",
  }),
  new CurrencyMetadata({
    alphaCode: "MMK",
    numCode: "104",
    minorUnit: 2,
    fullName: "Kyat",
  }),
  new CurrencyMetadata({
    alphaCode: "MNT",
    numCode: "496",
    minorUnit: 2,
    fullName: "Tugrik",
  }),
  new CurrencyMetadata({
    alphaCode: "MOP",
    numCode: "446",
    minorUnit: 2,
    fullName: "Pataca",
  }),
  new CurrencyMetadata({
    alphaCode: "MRU",
    numCode: "929",
    minorUnit: 2,
    fullName: "Ouguiya",
  }),
  new CurrencyMetadata({
    alphaCode: "MUR",
    numCode: "480",
    minorUnit: 2,
    fullName: "Mauritius Rupee",
  }),
  new CurrencyMetadata({
    alphaCode: "MVR",
    numCode: "462",
    minorUnit: 2,
    fullName: "Rufiyaa",
  }),
  new CurrencyMetadata({
    alphaCode: "MWK",
    numCode: "454",
    minorUnit: 2,
    fullName: "Malawi Kwacha",
  }),
  new CurrencyMetadata({
    alphaCode: "MXN",
    numCode: "484",
    minorUnit: 2,
    fullName: "Mexican Peso",
  }),
  new CurrencyMetadata({
    alphaCode: "MXV",
    numCode: "979",
    minorUnit: 2,
    fullName: "Mexican Unidad de Inversion (UDI)",
  }),
  new CurrencyMetadata({
    alphaCode: "MYR",
    numCode: "458",
    minorUnit: 2,
    fullName: "Malaysian Ringgit",
  }),
  new CurrencyMetadata({
    alphaCode: "MZN",
    numCode: "943",
    minorUnit: 2,
    fullName: "Mozambique Metical",
  }),
  new CurrencyMetadata({
    alphaCode: "NAD",
    numCode: "516",
    minorUnit: 2,
    fullName: "Namibia Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "NGN",
    numCode: "566",
    minorUnit: 2,
    fullName: "Naira",
  }),
  new CurrencyMetadata({
    alphaCode: "NIO",
    numCode: "558",
    minorUnit: 2,
    fullName: "Cordoba Oro",
  }),
  new CurrencyMetadata({
    alphaCode: "NOK",
    numCode: "578",
    minorUnit: 2,
    fullName: "Norwegian Krone",
  }),
  new CurrencyMetadata({
    alphaCode: "NPR",
    numCode: "524",
    minorUnit: 2,
    fullName: "Nepalese Rupee",
  }),
  new CurrencyMetadata({
    alphaCode: "NZD",
    numCode: "554",
    minorUnit: 2,
    fullName: "New Zealand Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "OMR",
    numCode: "512",
    minorUnit: 3,
    fullName: "Rial Omani",
  }),
  new CurrencyMetadata({
    alphaCode: "PAB",
    numCode: "590",
    minorUnit: 2,
    fullName: "Balboa",
  }),
  new CurrencyMetadata({
    alphaCode: "PEN",
    numCode: "604",
    minorUnit: 2,
    fullName: "Sol",
  }),
  new CurrencyMetadata({
    alphaCode: "PGK",
    numCode: "598",
    minorUnit: 2,
    fullName: "Kina",
  }),
  new CurrencyMetadata({
    alphaCode: "PHP",
    numCode: "608",
    minorUnit: 2,
    fullName: "Philippine Peso",
  }),
  new CurrencyMetadata({
    alphaCode: "PKR",
    numCode: "586",
    minorUnit: 2,
    fullName: "Pakistan Rupee",
  }),
  new CurrencyMetadata({
    alphaCode: "PLN",
    numCode: "985",
    minorUnit: 2,
    fullName: "Zloty",
  }),
  new CurrencyMetadata({
    alphaCode: "PYG",
    numCode: "600",
    minorUnit: 0,
    fullName: "Guarani",
  }),
  new CurrencyMetadata({
    alphaCode: "QAR",
    numCode: "634",
    minorUnit: 2,
    fullName: "Qatari Rial",
  }),
  new CurrencyMetadata({
    alphaCode: "RON",
    numCode: "946",
    minorUnit: 2,
    fullName: "Romanian Leu",
  }),
  new CurrencyMetadata({
    alphaCode: "RSD",
    numCode: "941",
    minorUnit: 2,
    fullName: "Serbian Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "RUB",
    numCode: "643",
    minorUnit: 2,
    fullName: "Russian Ruble",
  }),
  new CurrencyMetadata({
    alphaCode: "RWF",
    numCode: "646",
    minorUnit: 0,
    fullName: "Rwanda Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "SAR",
    numCode: "682",
    minorUnit: 2,
    fullName: "Saudi Riyal",
  }),
  new CurrencyMetadata({
    alphaCode: "SBD",
    numCode: "090",
    minorUnit: 2,
    fullName: "Solomon Islands Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "SCR",
    numCode: "690",
    minorUnit: 2,
    fullName: "Seychelles Rupee",
  }),
  new CurrencyMetadata({
    alphaCode: "SDG",
    numCode: "938",
    minorUnit: 2,
    fullName: "Sudanese Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "SEK",
    numCode: "752",
    minorUnit: 2,
    fullName: "Swedish Krona",
  }),
  new CurrencyMetadata({
    alphaCode: "SGD",
    numCode: "702",
    minorUnit: 2,
    fullName: "Singapore Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "SHP",
    numCode: "654",
    minorUnit: 2,
    fullName: "Saint Helena Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "SLL",
    numCode: "694",
    minorUnit: 2,
    fullName: "Leone",
  }),
  new CurrencyMetadata({
    alphaCode: "SOS",
    numCode: "706",
    minorUnit: 2,
    fullName: "Somali Shilling",
  }),
  new CurrencyMetadata({
    alphaCode: "SRD",
    numCode: "968",
    minorUnit: 2,
    fullName: "Surinam Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "SSP",
    numCode: "728",
    minorUnit: 2,
    fullName: "South Sudanese Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "STN",
    numCode: "930",
    minorUnit: 2,
    fullName: "Dobra",
  }),
  new CurrencyMetadata({
    alphaCode: "SVC",
    numCode: "222",
    minorUnit: 2,
    fullName: "El Salvador Colon",
  }),
  new CurrencyMetadata({
    alphaCode: "SYP",
    numCode: "760",
    minorUnit: 2,
    fullName: "Syrian Pound",
  }),
  new CurrencyMetadata({
    alphaCode: "SZL",
    numCode: "748",
    minorUnit: 2,
    fullName: "Lilangeni",
  }),
  new CurrencyMetadata({
    alphaCode: "THB",
    numCode: "764",
    minorUnit: 2,
    fullName: "Baht",
  }),
  new CurrencyMetadata({
    alphaCode: "TJS",
    numCode: "972",
    minorUnit: 2,
    fullName: "Somoni",
  }),
  new CurrencyMetadata({
    alphaCode: "TMT",
    numCode: "934",
    minorUnit: 2,
    fullName: "Turkmenistan New Manat",
  }),
  new CurrencyMetadata({
    alphaCode: "TND",
    numCode: "788",
    minorUnit: 3,
    fullName: "Tunisian Dinar",
  }),
  new CurrencyMetadata({
    alphaCode: "TOP",
    numCode: "776",
    minorUnit: 2,
    fullName: "Pa’anga",
  }),
  new CurrencyMetadata({
    alphaCode: "TRY",
    numCode: "949",
    minorUnit: 2,
    fullName: "Turkish Lira",
  }),
  new CurrencyMetadata({
    alphaCode: "TTD",
    numCode: "780",
    minorUnit: 2,
    fullName: "Trinidad and Tobago Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "TWD",
    numCode: "901",
    minorUnit: 2,
    fullName: "New Taiwan Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "TZS",
    numCode: "834",
    minorUnit: 2,
    fullName: "Tanzanian Shilling",
  }),
  new CurrencyMetadata({
    alphaCode: "UAH",
    numCode: "980",
    minorUnit: 2,
    fullName: "Hryvnia",
  }),
  new CurrencyMetadata({
    alphaCode: "UGX",
    numCode: "800",
    minorUnit: 0,
    fullName: "Uganda Shilling",
  }),
  new CurrencyMetadata({
    alphaCode: "USD",
    numCode: "840",
    minorUnit: 2,
    fullName: "US Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "USN",
    numCode: "997",
    minorUnit: 2,
    fullName: "US Dollar (Next day)",
  }),
  new CurrencyMetadata({
    alphaCode: "UYI",
    numCode: "940",
    minorUnit: 0,
    fullName: "Uruguay Peso en Unidades Indexadas (UI)",
  }),
  new CurrencyMetadata({
    alphaCode: "UYU",
    numCode: "858",
    minorUnit: 2,
    fullName: "Peso Uruguayo",
  }),
  new CurrencyMetadata({
    alphaCode: "UYW",
    numCode: "927",
    minorUnit: 4,
    fullName: "Unidad Previsional",
  }),
  new CurrencyMetadata({
    alphaCode: "UZS",
    numCode: "860",
    minorUnit: 2,
    fullName: "Uzbekistan Sum",
  }),
  new CurrencyMetadata({
    alphaCode: "VES",
    numCode: "928",
    minorUnit: 2,
    fullName: "Bolívar Soberano",
  }),
  new CurrencyMetadata({
    alphaCode: "VND",
    numCode: "704",
    minorUnit: 0,
    fullName: "Dong",
  }),
  new CurrencyMetadata({
    alphaCode: "VUV",
    numCode: "548",
    minorUnit: 0,
    fullName: "Vatu",
  }),
  new CurrencyMetadata({
    alphaCode: "WST",
    numCode: "882",
    minorUnit: 2,
    fullName: "Tala",
  }),
  new CurrencyMetadata({
    alphaCode: "XAF",
    numCode: "950",
    minorUnit: 0,
    fullName: "CFA Franc BEAC",
  }),
  new CurrencyMetadata({
    alphaCode: "XAG",
    numCode: "961",
    minorUnit: null,
    fullName: "Silver",
  }),
  new CurrencyMetadata({
    alphaCode: "XAU",
    numCode: "959",
    minorUnit: null,
    fullName: "Gold",
  }),
  new CurrencyMetadata({
    alphaCode: "XBA",
    numCode: "955",
    minorUnit: null,
    fullName: "Bond Markets Unit European Composite Unit (EURCO)",
  }),
  new CurrencyMetadata({
    alphaCode: "XBB",
    numCode: "956",
    minorUnit: null,
    fullName: "Bond Markets Unit European Monetary Unit (E.M.U.-6)",
  }),
  new CurrencyMetadata({
    alphaCode: "XBC",
    numCode: "957",
    minorUnit: null,
    fullName: "Bond Markets Unit European Unit of Account 9 (E.U.A.-9)",
  }),
  new CurrencyMetadata({
    alphaCode: "XBD",
    numCode: "958",
    minorUnit: null,
    fullName: "Bond Markets Unit European Unit of Account 17 (E.U.A.-17)",
  }),
  new CurrencyMetadata({
    alphaCode: "XCD",
    numCode: "951",
    minorUnit: 2,
    fullName: "East Caribbean Dollar",
  }),
  new CurrencyMetadata({
    alphaCode: "XDR",
    numCode: "960",
    minorUnit: null,
    fullName: "SDR (Special Drawing Right)",
  }),
  new CurrencyMetadata({
    alphaCode: "XOF",
    numCode: "952",
    minorUnit: 0,
    fullName: "CFA Franc BCEAO",
  }),
  new CurrencyMetadata({
    alphaCode: "XPD",
    numCode: "964",
    minorUnit: null,
    fullName: "Palladium",
  }),
  new CurrencyMetadata({
    alphaCode: "XPF",
    numCode: "953",
    minorUnit: 0,
    fullName: "CFP Franc",
  }),
  new CurrencyMetadata({
    alphaCode: "XPT",
    numCode: "962",
    minorUnit: null,
    fullName: "Platinum",
  }),
  new CurrencyMetadata({
    alphaCode: "XSU",
    numCode: "994",
    minorUnit: null,
    fullName: "Sucre",
  }),
  new CurrencyMetadata({
    alphaCode: "XTS",
    numCode: "963",
    minorUnit: null,
    fullName: "Codes specifically reserved for testing purposes",
  }),
  new CurrencyMetadata({
    alphaCode: "XUA",
    numCode: "965",
    minorUnit: null,
    fullName: "ADB Unit of Account",
  }),
  new CurrencyMetadata({
    alphaCode: "XXX",
    numCode: "999",
    minorUnit: null,
    fullName: "The codes assigned for transactions where no currency is involved",
  }),
  new CurrencyMetadata({
    alphaCode: "YER",
    numCode: "886",
    minorUnit: 2,
    fullName: "Yemeni Rial",
  }),
  new CurrencyMetadata({
    alphaCode: "ZAR",
    numCode: "710",
    minorUnit: 2,
    fullName: "Rand",
  }),
  new CurrencyMetadata({
    alphaCode: "ZMW",
    numCode: "967",
    minorUnit: 2,
    fullName: "Zambian Kwacha",
  }),
  new CurrencyMetadata({
    alphaCode: "ZWL",
    numCode: "932",
    minorUnit: 2,
    fullName: "Zimbabwe Dollar",
  }),
];
